name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "plateRecognition/train_models.py"
      - ".github/workflows/ci_cd.yml"
  pull_request:
    branches:
      - main
    paths:
      - "plateRecognition/train_models.py"
      - ".github/workflows/ci_cd.yml"

jobs:
  train-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create models directory
        run: mkdir -p models

      - name: Train and save models
        run: python plateRecognition/train_models.py

      - name: Commit and Push models
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git        
          git add models/*.pkl
          git commit -m "Update models via GitHub Actions" || echo "No changes to commit"
          git push

  deploy-api:
    needs: train-models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install API dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Trigger Render deploy
        run: |
          pip install requests
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "do_not_clear"}' \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
